#application
spring.application.name=e-commerce
sever.port=8080

#database
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce_database
spring.datasource.driver-class-name=org.postgresql.Driver
#hibernate
spring.jpa.hibernate.ddl-auto=create-only
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

